i
have
a
ruby
on
rails
website
that
make
http
call
to
an
external
web
service
.
about
once
a
day
i
get
a
systemexit
(
stacktrace
below
)
error
email
where
a
call
to
the
service
ha
failed
.
if
i
then
try
the
exact
same
query
on
my
site
moment
later
it
work
fine
.
it
's
been
happening
since
the
site
went
live
and
i
've
had
no
luck
tracking
down
what
cause
it
.
ruby
is
version
1.8.6
and
rail
is
version
1.2.6
.
anyone
else
have
this
problem
?
this
is
the
error
and
stacktrace
.
a
systemexit
occurred
/usr/local/lib/ruby/gems/1.8/gems/rails-1.2.6/lib/fcgi_handler.rb:116
:
in
`exit
'
/usr/local/lib/ruby/gems/1.8/gems/rails-1.2.6/lib/fcgi_handler.rb:116
:
in
`exit_now_handler
'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-1.4.4/lib/active_support/inflector.rb:250
:
in
`to_proc
'
/usr/local/lib/ruby/1.8/net/protocol.rb:133
:
in
`call
'
/usr/local/lib/ruby/1.8/net/protocol.rb:133
:
in
`sysread
'
/usr/local/lib/ruby/1.8/net/protocol.rb:133
:
in
`rbuf_fill
'
/usr/local/lib/ruby/1.8/timeout.rb:56
:
in
`timeout
'
/usr/local/lib/ruby/1.8/timeout.rb:76
:
in
`timeout
'
/usr/local/lib/ruby/1.8/net/protocol.rb:132
:
in
`rbuf_fill
'
/usr/local/lib/ruby/1.8/net/protocol.rb:116
:
in
`readuntil
'
/usr/local/lib/ruby/1.8/net/protocol.rb:126
:
in
`readline
'
/usr/local/lib/ruby/1.8/net/http.rb:2017
:
in
`read_status_line
'
/usr/local/lib/ruby/1.8/net/http.rb:2006
:
in
`read_new
'
/usr/local/lib/ruby/1.8/net/http.rb:1047
:
in
`request
'
/usr/local/lib/ruby/1.8/net/http.rb:945
:
in
`request_get
'
/usr/local/lib/ruby/1.8/net/http.rb:380
:
in
`get_response
'
/usr/local/lib/ruby/1.8/net/http.rb:543
:
in
`start
'
/usr/local/lib/ruby/1.8/net/http.rb:379
:
in
`get_response
'