exceptions
in
c++
do
n't
need
to
be
caught
(
no
compile
time
error
)
by
the
calling
function
.
so
it
's
up
to
developer
's
judgment
whether
to
catch
it
using
try/catch
(
unlike
in
java
)
.
is
there
a
way
one
can
ensure
that
the
exception
thrown
are
always
caught
using
try/catch
by
the
calling
function
?